# Generated by Django 4.2.20 on 2025-04-27 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dacha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('single_bed_room_count', models.PositiveSmallIntegerField()),
                ('double_bed_room_count', models.PositiveSmallIntegerField()),
                ('enter_time', models.TimeField()),
                ('exit_time', models.TimeField()),
                ('room_count', models.PositiveSmallIntegerField()),
                ('week_day_price', models.PositiveIntegerField()),
                ('week_end_price', models.PositiveIntegerField()),
                ('square_meter', models.PositiveIntegerField()),
                ('alcohol', models.BooleanField(default=False)),
                ('available_only_family', models.BooleanField(default=False)),
                ('loudly_music', models.BooleanField(default=False)),
                ('party', models.BooleanField(default=False)),
                ('pets', models.BooleanField(default=False)),
                ('smoking', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('playstation_5', models.BooleanField(default=False)),
                ('playstation_4', models.BooleanField(default=False)),
                ('playstation_3', models.BooleanField(default=False)),
                ('air_conditioner', models.BooleanField(default=False)),
                ('billiards', models.BooleanField(default=False)),
                ('table_tennis', models.BooleanField(default=False)),
                ('football_field', models.BooleanField(default=False)),
                ('karaoke', models.BooleanField(default=False)),
                ('sauna', models.BooleanField(default=False)),
                ('jacuzzi', models.BooleanField(default=False)),
                ('turkish_bath', models.BooleanField(default=False)),
                ('indoor_swimming_pool', models.BooleanField(default=False)),
                ('outdoor_swimming_pool', models.BooleanField(default=False)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.CharField(choices=[('verified', 'Verified'), ('not_verified', 'Not Verified'), ('new', 'New')], default='new', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DachaReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rating', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dacha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='DachaApp.dacha')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DachaReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dacha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='DachaApp.dacha')),
            ],
        ),
        migrations.CreateModel(
            name='DachaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dacha_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dacha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='DachaApp.dacha')),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dacha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_by', to='DachaApp.dacha')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'dacha')},
            },
        ),
    ]
