# Generated by Django 4.2.20 on 2025-04-29 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DachaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='dacha',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='dacha_images/'),
        ),
        migrations.AddField(
            model_name='dacha',
            name='image10',
            field=models.ImageField(blank=True, null=True, upload_to='dacha_images/'),
        ),
        migrations.AddField(
            model_name='dacha',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='dacha_images/'),
        ),
        migrations.AddField(
            model_name='dacha',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='dacha_images/'),
        ),
        migrations.AddField(
            model_name='dacha',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='dacha_images/'),
        ),
        migrations.AddField(
            model_name='dacha',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='dacha_images/'),
        ),
        migrations.AddField(
            model_name='dacha',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='dacha_images/'),
        ),
        migrations.AddField(
            model_name='dacha',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='dacha_images/'),
        ),
        migrations.AddField(
            model_name='dacha',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='dacha_images/'),
        ),
        migrations.AddField(
            model_name='dacha',
            name='image9',
            field=models.ImageField(blank=True, null=True, upload_to='dacha_images/'),
        ),
        migrations.DeleteModel(
            name='DachaImage',
        ),
        migrations.AddField(
            model_name='dacha',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DachaApp.category'),
        ),
    ]
