# Generated by Django 4.2.20 on 2025-04-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DachaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dacha',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
