# Generated by Django 4.2.20 on 2025-04-24 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DachaApp', '0002_dacha_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dacha',
            name='is_verified',
            field=models.CharField(choices=[('verified', 'Verified'), ('not_verified', 'Not Verified'), ('new', 'New')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='dachaaddress',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dachaaddress',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dachaaddress',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dachaaddress',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dachareservation',
            name='check_in',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='dachareservation',
            name='check_out',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dacha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DachaApp.dacha')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
