# Generated by Django 4.2.20 on 2025-04-25 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DachaApp', '0003_alter_dacha_is_verified_alter_dachaaddress_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dacha',
            name='air_conditioner',
        ),
        migrations.RemoveField(
            model_name='dacha',
            name='alcohol',
        ),
        migrations.RemoveField(
            model_name='dacha',
            name='available_only_family',
        ),
        migrations.RemoveField(
            model_name='dacha',
            name='billiards',
        ),
        migrations.RemoveField(
            model_name='dacha',
            name='category',
        ),
        migrations.RemoveField(
            model_name='dacha',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='dacha',
            name='description',
        ),
        migrations.RemoveField(
            model_name='dacha',
            name='double_bed_room_count',
        ),
        migrations.RemoveField(
            model_name='dacha',
            name='enter_time',
        ),
        migrations.RemoveField(
            model_name='dacha',
            name='exit_time',
        ),
        migrations.RemoveField(
            model_name='dacha',
            name='football_field',
        ),
        migrations.RemoveField(
            model_name='dacha',
            name='indoor_swimming_pool',
        ),
        migrations.RemoveField(
            model_name='dacha',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='dacha',
            name='jacuzzi',
        ),
        migrations.RemoveField(
            model_name='dacha',
            name='karaoke',
        ),
        migrations.RemoveField(
            model_name='dacha',
            name='loudly_music',
        ),
        migrations.RemoveField(
            model_name='dacha',
            name='outdoor_swimming_pool',
        ),
        migrations.RemoveField(
            model_name='dacha',
            name='party',
        ),
        migrations.RemoveField(
            model_name='dacha',
            name='pets',
        ),
        migrations.RemoveField(
            model_name='dacha',
            name='playstation_3',
        ),
        migrations.RemoveField(
            model_name='dacha',
            name='playstation_4',
        ),
        migrations.RemoveField(
            model_name='dacha',
            name='playstation_5',
        ),
        migrations.RemoveField(
            model_name='dacha',
            name='room_count',
        ),
        migrations.RemoveField(
            model_name='dacha',
            name='sauna',
        ),
        migrations.RemoveField(
            model_name='dacha',
            name='single_bed_room_count',
        ),
        migrations.RemoveField(
            model_name='dacha',
            name='smoking',
        ),
        migrations.RemoveField(
            model_name='dacha',
            name='square_meter',
        ),
        migrations.RemoveField(
            model_name='dacha',
            name='table_tennis',
        ),
        migrations.RemoveField(
            model_name='dacha',
            name='turkish_bath',
        ),
        migrations.RemoveField(
            model_name='dacha',
            name='week_day_price',
        ),
        migrations.RemoveField(
            model_name='dacha',
            name='week_end_price',
        ),
        migrations.RemoveField(
            model_name='dacha',
            name='wifi',
        ),
        migrations.RemoveField(
            model_name='dachaaddress',
            name='city',
        ),
        migrations.RemoveField(
            model_name='dachaaddress',
            name='country',
        ),
        migrations.RemoveField(
            model_name='dachaaddress',
            name='district',
        ),
        migrations.RemoveField(
            model_name='dachaaddress',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='dachaaddress',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='dachaaddress',
            name='region',
        ),
        migrations.AddField(
            model_name='dacha',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dacha',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dacha',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dacha',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dacha',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dacha',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='dacha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_by', to='DachaApp.dacha'),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='favorites',
            unique_together={('user', 'dacha')},
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
