# Generated by Django 4.2.20 on 2025-04-25 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DachaApp', '0004_remove_dacha_air_conditioner_remove_dacha_alcohol_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DachaAddress',
        ),
    ]
